# fly.toml app configuration file generated for part-3-shy-wildflower-6331 on 2024-09-15T00:33:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part-3-shy-wildflower-6331'
primary_region = 'yyz'

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
